### ISSUE TITLE
Q: AIP-151: dont error on custom operation method

### ISSUE THREAD

**Issue by loeffel-io** [googleapis/api-linter#1428]
As mentioned [here](https://github.com/googleapis/googleapis/blob/master/google/longrunning/operations.proto#L62) you can add custom bindings. This sounds to me that we can create our own GetOperation/ListOperations method inside our own GrpcService like:

```proto
  rpc GetOperation(GetOperationRequest) returns (google.longrunning.Operation) {
    option (google.api.http) = {
      get: "/v1/{name=projects/*/emails/*/operations/*}"
    };
    option (google.api.method_signature) = "name";
  }
```

but this will fail with 

```
- file_path: mindful/earth/email/v1/email.proto
  problems:
    - message: Methods returning an LRO must include the operation_info annotation.
      location:
        start_position:
            line_number: 77
            column_number: 3
        end_position:
            line_number: 82
            column_number: 3
        path: mindful/earth/email/v1/email.proto
      rule_id: core::0151::operation-info
      rule_doc_uri: https://linter.aip.dev/151/operation-info
```

Maybe i can get some insights here, thank you 🙏
