### ISSUE TITLE
Spurious "Create methods should include `parent`" warning

### ISSUE THREAD

**Issue by drigz** [googleapis/api-linter#408]
Service:

```
  rpc CreateProject(CreateProjectRequest) returns (Project) {
    option (google.api.http) = {
      post: "/v1alpha1/{parent=organizations/*}/projects"
      body: "project"
    };
  }
```

Warning:

```
  - message: Create methods should include the `parent` field in the URI.
    location:
      start_position:
        line_number: 52
        column_number: 3
      end_position:
        line_number: 57
        column_number: 3
    rule_id: core::0133::http-uri-parent
    rule_doc_uri: https://linter.aip.dev/133/http-uri-parent
```

I can't work out what I'm missing here as the my service seems identical to the example from the docs.
