### ISSUE TITLE
AIP-203. False detection

### ISSUE THREAD

**Issue by valery-barysok** [googleapis/api-linter#621]
Example:
```
message CreateRoleRequest {

  // Required. The role to create.
  // Fields marked `OutputOnly` must be left blank.
  Role role = 2 [(google.api.field_behavior) = REQUIRED];
}
```

Leads to 
```
  - message: Use the `google.api.field_behavior` annotation instead of " Fields marked `OutputOnly` must be left blank." in the leading comments. For example, `string name = 1 [(google.api.field_behavior) = OUTPUT_ONLY];`.
    location:
      start_position:
        line_number: 63
        column_number: 3
      end_position:
        line_number: 63
        column_number: 57
    rule_id: core::0203::output-only
    rule_doc_uri: https://linter.aip.dev/203/output-only
```

I think it should not check REQUIRED and OUTPUT_ONLY separately. The same should be for other combinations of field behavior options.

May be It should look for specified field behavior options and if there are some of them check for them only.
